name: Bank Frontend Pipeline

on:
  push:
    branches:
      - main

jobs:
  Continues-Integration_build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: sam-osung/banking-app-with-k8s
          ref: main

      - name: Log in to awscli
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build container image
        run: docker build -t bank-app-frontend:latest .

      - name: Log in to ECR with short-lived credentials
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ vars.ECR_REPO }}

      - name: Tag Docker image
        run: docker tag bank-app-frontend:latest ${{ vars.ECR_REPO }}/bank-frontend:${{ github.run_number }}

      - name: Push image to ECR
        run: docker push ${{ vars.ECR_REPO }}/bank-frontend:${{ github.run_number }}

      - name: Clean up Docker image locally
        run: |
          docker rmi bank-app-frontend:latest
          docker rmi ${{ vars.ECR_REPO }}/bank-frontend:${{ github.run_number }}

      - name: Clean up GitHub repo on runner
        run: rm -rf ./*

  Continues-Update_k8s_manifest:
    runs-on: ubuntu-latest
    needs: Continues-Integration_build_and_push

    steps:
      # Checkout the manifests repo
      - name: Checkout Kubernetes manifest repo
        uses: actions/checkout@v3
        with:
          repository: sam-osung/banking-app-with-k8s
          ref: main
          persist-credentials: false  # Important: disables using github-actions bot token

      # Configure Git
      - name: Configure Git
        run: |
          git config --global user.email "osung996@gmail.com"
          git config --global user.name "sam-osung"

      # Update image tag
      - name: Update frontend image tag
        run: |
          sed -i "s+${{ vars.ECR_REPO }}/bank-frontend:.*+${{ vars.ECR_REPO }}/bank-frontend:${{ github.run_number }}+g" ./bankapp-manifests/frontend-deployment.yaml
          git add ./bankapp-manifests/frontend-deployment.yaml
          git commit -m "Update frontend image to version ${{ github.run_number }}" || echo "No changes to commit"

      # Push changes using PAT
      - name: Push updated manifest
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        run: |
          git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/sam-osung/banking-app-with-k8s.git main